apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fx08
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0006-tenant/tkrw-pr712-0075-0006-app/devfile-sample-fx08@sha256:9d79a38ca1e578227b5de7726325db951fff5cd6b3cce56dbf3d3ee5abb1ef65
        name: my-nodejs
        resources: {}
status: {}
